name: Bug report
description: Create a report to help us improve
labels: ['bug']
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: textarea
    id: describe-bug
    attributes:
      label: Describe the bug
      description: A clear and concise description of what the bug is.
      placeholder: Tell us what you see!
    validations:
      required: true
  - type: textarea
    id: impact
    attributes:
      label: Impact
      description: Describe the impact of the bug, on users, developers, data consistency or increased risk. Should it be fixed soon, or can it wait?
    validations:
      required: true
  - type: dropdown
    id: environment
    attributes:
      label: environment
      description: What environment does this happen in at time of reporting?
      options:
        - production
        - nightly
        - dev
        - all of the above
      default: 0
    validations:
      required: true
  - type: textarea
    id: to-reproduce
    attributes:
      label: Steps to reproduce the behaviour
      placeholder: |
        1. go to '...'
        2. click on '...'
        3. then you see '...'
    validations:
      required: true
  - type: textarea
    id: expected-behaviour
    attributes:
      label: A clear and concise description of what you expected to happen.
  - type: textarea
    id: screenshots
    attributes:
      label: any screenshots or movies of the bug
      description: You can attach images or log files by clicking this area to highlight it and then dragging files in.
  - type: textarea
    id: additional-context
    attributes:
      label: Additional context
      description: Add any other context about the problem here.

